---
- name: BIG-IQ and AS3 Lab - Task 10 - Deploy the HTTP Application Service using an FQDN pool to identify pool members
  hosts: "{{ env }}"
  vars_files:
    - inventory/group_vars/{{ env }}.yml

  tasks: 
    - name: Get BIG-IQ Token POST /mgmt/shared/authn/login (auth_bigiq_<user>.json)
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/authn/login
        method: POST
        headers:
          Content-Type: application/json
        body: "{{ lookup('file','{{ user }}') }}"
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth

    - name: Task 10 - Deploy the HTTP Application Service using an FQDN pool to identify pool members - POST /mgmt/shared/appsvcs/declare?async=true
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/declare?async=true
        method: POST
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        body:
          # used https://www.json2yaml.com/ to convert JSON declaration to YAML
          class: AS3
          action: deploy
          persist: true
          declaration:
            class: ADC
            schemaVersion: "{{ as3_schemaVersion }}"
            id: example-declaration-01
            label: Task10
            remark: Task 10 - FQDN pool members
            target:
              hostname: "{{ bigip_target }}"
            Task10:
              class: Tenant
              MyWebApp10fqdn:
                class: Application
                template: http
                statsProfile:
                  class: Analytics_Profile
                  collectClientSideStatistics: true
                  collectOsAndBrowser: false
                  collectMethod: false
                serviceMain:
                  class: Service_HTTP
                  virtualAddresses:
                  - "{{ task10_vs }}"
                  pool: fqdn_pool
                  persistenceMethods:
                  - cookie
                  profileHTTP: basic
                  layer4: tcp
                  profileTCP: normal
                  snat: auto
                  profileAnalytics:
                    use: statsProfile
                fqdn_pool:
                  class: Pool
                  monitors:
                  - http
                  members:
                  - servicePort: 80
                    addressDiscovery: fqdn
                    autoPopulate: true
                    hostname: "{{ task10_hostname }}"
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response

    - debug:
        var: json_response.json

### LOOP TO CHECK THE TASK - DO NOT MODIFY BELOW

    - name: Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response_task

    - debug:
        var: json_response_task.json

    - name: LOOP Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        status_code: 200, 202
        validate_certs: false
      register: json_response_task
      until: "json_response_task.json[0].results[0].message != 'in progress'"
      retries: 20
      delay: 30

    - debug:
        var: json_response_task.json